#count: count.cpp test-lls.cpp
#	g++ -o count -ggdb3 -Wall -Werror -pedantic -std=gnu++98 count.cpp
intTest: test-lls.cpp ll.hpp
	g++ -o intTest -ggdb3 -Wall -Werror -pedantic -std=gnu++98 test-lls.cpp
